### ISSUE TITLE
Why do we have beforeShowing empty?

### ISSUE THREAD

**Issue by akevalion** [sambegou122/DLPoster#12]
Maybe in this case we can leave the class with 

```st
DataChart >> #beforeShowing

```

And subclasses only are going to define it when they need it

**Comment by sambegou122** [comment]
doing

**Comment by akevalion** [comment]
Can you reopen the issue, it is not finish, because I can see the beforeShowing.
In this case DataChart hierarchy is not being used, then we can discard the issue if the hierarchy is removed from the repository
