### ISSUE TITLE
We should show floats when we need it

### ISSUE THREAD

**Issue by akevalion** [sambegou122/DLPoster#27]
Consider this example
```st
	| x y plots perlin |
	perlin := NSPerlinNoise3 new octaves: 5.
	
	x := 0.0 to: 2 count: 10.
	plots := (1 to: 4) collect: [ :index | 
		y := x collect: [ :n | perlin noise: index and: n ].
		DCBarPlot new
			x: x;
			y: y;
			yourself ].
	
	^ (DCClusterBarPlot withAll: plots)
		title: 'Cluster Bar Plot';
		xlabel: 'X Axis';
		ylabel: 'Y Axis';
		build;
		show.
```

<img width="530" alt="image" src="https://user-images.githubusercontent.com/10532890/169060356-767fcf18-784f-4a05-8fd9-1d39353df7e2.png">

The image in axis is only showing integer number, in this case it should consider floats when we have floats.

**Comment by sambegou122** [comment]
![datatypefixed](https://user-images.githubusercontent.com/98162905/169285033-ddda72e7-7559-4af1-aa7c-7006a3bd9325.png)
 
fixed
