### ISSUE TITLE
white space in histogram

### ISSUE THREAD

**Issue by akevalion** [sambegou122/DLPoster#29]
There is a white space in histogram

<img width="463" alt="image" src="https://user-images.githubusercontent.com/10532890/169064100-154abb8d-9640-4b12-a767-efb7445d8d2d.png">

**Comment by sambegou122** [comment]
![histoey](https://user-images.githubusercontent.com/98162905/169540590-836762c0-6ae8-47ee-b62c-23f1800f444c.png)
 fixed*
