### ISSUE TITLE
red tests

### ISSUE THREAD

**Issue by akevalion** [sambegou122/DLPoster#4]
Currently there is an error with tests
<img width="663" alt="image" src="https://user-images.githubusercontent.com/10532890/165065541-dc9d705e-3190-43f1-8cba-62ca6c2fe1a2.png">

**Comment by akevalion** [comment]
There is an update but still we do not have green tests
<img width="648" alt="image" src="https://user-images.githubusercontent.com/10532890/165082773-45ede8b3-e746-40e0-9397-6478eed04511.png">
Possible we will need a CI to control the tests

**Comment by sambegou122** [comment]
That 's fixed

**Comment by akevalion** [comment]
Done!
