### ISSUE TITLE
Create a combined chart

### ISSUE THREAD

**Issue by akevalion** [sambegou122/DLPoster#8]
For example check this example RSChartExample >> #example03Plot and transform it into a class that we can reuse with different values

please also provide tests for that

Maybe we can use this 
```st
| x line1 line2 line3 |

x := 0.0 to: 2 count: 100.

line1 := LinePlot new
	x: x;
	y: (x raisedTo: 2);
	yourself.

line2 := LinePlot new
	x: x;
	y: (x raisedTo: 3);
	yourself.
	
line1 := LinePlot new
	x: x;
	y: (x raisedTo: 3);
	yourself.
	
combined := CombinedPlot withAll: { line1. line2. line3 }.
combined 
	title: 'Hello world'.
	xtitle: 'X Axis'
	ytitle: 'Y Axis';
	show
```

<img width="423" alt="image" src="https://user-images.githubusercontent.com/10532890/166209220-19820e25-8347-4fa3-9ce9-cc9c526496b8.png">

**Comment by sambegou122** [comment]
finish
